import { Router } from "express";
import * as controller from "../controllers/admin.controller";
import { adminMiddleware } from "../middlewares/admin.middleware";
export const adminRoutes = Router();
adminRoutes.use(adminMiddleware);
adminRoutes.post("/import-matches", controller.importMatches);
adminRoutes.post("/import-matches-json", controller.importJson);
adminRoutes.post("/recalculate-points", controller.recalculate);
adminRoutes.post("/sync-knockout-bracket", controller.syncBracket);
adminRoutes.get("/official-champion", controller.officialChampion);
adminRoutes.put("/official-champion", controller.saveChampion);
adminRoutes.delete("/official-champion", controller.clearChampion);
adminRoutes.get("/results-preview", controller.previewResults);
adminRoutes.post("/results-apply", controller.applyResults);
