import { FormEvent, useEffect, useState } from "react";
import { api, errorMessage } from "../api/client";
import { AdminMatchForm } from "../components/AdminMatchForm";
import { Match, OfficialChampionState, ResultPreview, ResultPreviewResponse } from "../types";
const sample = `{"matches":[{"externalId":"match-001","homeTeam":"Alemania","awayTeam":"Curazao","matchDate":"2026-06-15T18:00:00.000Z","stage":"GROUP","groupName":"Grupo A"}]}`;
export const AdminPage = () => {
  const [matches, setMatches] = useState<Match[]>([]); const [message, setMessage] = useState(""); const [json, setJson] = useState(sample);
  const [officialChampion, setOfficialChampion] = useState<OfficialChampionState>(); const [championTeam, setChampionTeam] = useState("");
  const [resultPreview, setResultPreview] = useState<ResultPreview[]>([]); const [selectedResults, setSelectedResults] = useState<number[]>([]); const [searchingResults, setSearchingResults] = useState(false); const [resultApiMessage, setResultApiMessage] = useState("");
  const [user, setUser] = useState({ name: "", username: "", password: "", role: "PLAYER" }); const [result, setResult] = useState({ matchId: "", homeScore: "", awayScore: "" });
  const load = () => api.get<Match[]>("/matches").then(({ data }) => setMatches(data));
  const loadChampion = () => api.get<OfficialChampionState>("/admin/official-champion").then(({ data }) => { setOfficialChampion(data); setChampionTeam(data.team ?? ""); });
  useEffect(() => { void load(); void loadChampion(); }, []);
  const run = async (action: () => Promise<unknown>, success: string) => { setMessage(""); try { await action(); setMessage(success); load(); } catch (e) { setMessage(errorMessage(e)); } };
  const createUser = (e: FormEvent) => { e.preventDefault(); run(() => api.post("/users", user), "Usuario creado"); };
  const saveResult = (e: FormEvent) => { e.preventDefault(); run(() => api.patch(`/matches/${result.matchId}/result`, { homeScore: Number(result.homeScore), awayScore: Number(result.awayScore) }), "Resultado guardado y puntos recalculados"); };
  const searchResults = async () => {
    setSearchingResults(true); setMessage(""); setResultApiMessage("");
    try {
      const { data } = await api.get<ResultPreviewResponse>("/admin/results-preview");
      setResultPreview(data.results); setSelectedResults(data.results.filter((item) => !item.alreadyLoaded).map((item) => item.matchId));
      const statuses = Object.entries(data.statusSummary).map(([status, count]) => `${status}: ${count}`).join(", ");
      const detail = data.results.length
        ? `${data.results.length} resultados encontrados (${data.results.filter((item) => !item.alreadyLoaded).length} nuevos).`
        : data.externalCount
          ? `La API trajo ${data.externalCount} resultado(s) finalizado(s), pero no coincidieron con el fixture cargado.`
          : data.apiMatchCount
            ? `La API respondió con ${data.apiMatchCount} partido(s), pero ninguno figura como finalizado. Estados recibidos: ${statuses}.`
            : "La API respondió bien, pero no devolvió partidos para este torneo.";
      setResultApiMessage(detail); setMessage(detail);
    } catch (e) { const detail = errorMessage(e); setResultApiMessage(detail); setMessage(detail); } finally { setSearchingResults(false); }
  };
  const toggleResult = (matchId: number) => setSelectedResults((current) => current.includes(matchId) ? current.filter((id) => id !== matchId) : [...current, matchId]);
  return <><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-300">Gestión</p><h1 className="mt-1 text-3xl font-black">Panel admin</h1>{message && <p className="my-4 rounded-xl bg-blue-500/10 p-3 text-sm text-blue-200">{message}</p>}<section className="mt-5 grid gap-4 lg:grid-cols-2">
    <div className="panel"><h2 className="mb-4 text-lg font-black">Crear usuario</h2><form className="grid gap-3" onSubmit={createUser}><input required placeholder="Nombre" value={user.name} onChange={(e) => setUser({ ...user, name: e.target.value })}/><input required placeholder="Usuario" value={user.username} onChange={(e) => setUser({ ...user, username: e.target.value })}/><input required minLength={6} type="password" placeholder="Contraseña" value={user.password} onChange={(e) => setUser({ ...user, password: e.target.value })}/><select value={user.role} onChange={(e) => setUser({ ...user, role: e.target.value })}><option value="PLAYER">Jugador</option><option value="ADMIN">Administrador</option></select><button className="button-primary">Crear usuario</button></form></div>
    <div className="panel"><h2 className="mb-4 text-lg font-black">Crear partido</h2><AdminMatchForm onCreated={load}/></div>
    <div className="panel"><h2 className="mb-4 text-lg font-black">Cargar resultado oficial</h2><form className="grid gap-3" onSubmit={saveResult}><select required value={result.matchId} onChange={(e) => setResult({ ...result, matchId: e.target.value })}><option value="">Seleccionar partido</option>{matches.map((match) => <option key={match.id} value={match.id}>{match.homeTeam} vs {match.awayTeam}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required min="0" type="number" placeholder="Goles local" value={result.homeScore} onChange={(e) => setResult({ ...result, homeScore: e.target.value })}/><input required min="0" type="number" placeholder="Goles visitante" value={result.awayScore} onChange={(e) => setResult({ ...result, awayScore: e.target.value })}/></div><button className="button-primary">Guardar resultado</button></form></div>
    <div className="panel"><h2 className="mb-4 text-lg font-black">Importar partidos por JSON</h2><textarea className="min-h-40 w-full font-mono text-xs" value={json} onChange={(e) => setJson(e.target.value)}/><button className="button-primary mt-3 w-full" onClick={() => run(() => api.post("/admin/import-matches-json", JSON.parse(json)), "Importación completada")}>Importar JSON</button></div>
    <div className="panel lg:col-span-2"><h2 className="text-lg font-black">Campeón oficial</h2><p className="my-2 text-sm text-slate-400">Al guardar el campeón, cada jugador que lo predijo recibe automáticamente {officialChampion?.bonusPoints ?? 15} puntos en la tabla general.</p><div className="flex flex-col gap-3 sm:flex-row"><select className="min-w-0 flex-1" value={championTeam} onChange={(e) => setChampionTeam(e.target.value)}><option value="">Seleccionar selección</option>{officialChampion?.teams.map((team) => <option key={team}>{team}</option>)}</select><button className="button-primary" disabled={!championTeam} onClick={() => run(async () => { await api.put("/admin/official-champion", { team: championTeam }); await loadChampion(); }, "Campeón oficial guardado")}>Guardar campeón</button><button className="button-secondary" disabled={!officialChampion?.team} onClick={() => run(async () => { await api.delete("/admin/official-champion"); await loadChampion(); }, "Campeón oficial eliminado")}>Limpiar</button></div></div>
    <div className="panel lg:col-span-2"><h2 className="text-lg font-black">Resultados desde API</h2><p className="my-2 text-sm text-slate-400">Busca resultados finalizados en la API configurada, revisa la vista previa y confirma los que quieras aplicar.</p><div className="flex flex-wrap gap-2"><button className="button-secondary" disabled={searchingResults} onClick={() => void searchResults()}>{searchingResults ? "Buscando..." : "Buscar resultados ahora"}</button><button className="button-primary" disabled={!selectedResults.length} onClick={() => run(async () => { await api.post("/admin/results-apply", { matchIds: selectedResults }); setResultPreview([]); setSelectedResults([]); setResultApiMessage(""); await load(); }, "Resultados aplicados y puntos recalculados")}>Confirmar seleccionados ({selectedResults.length})</button></div>{resultApiMessage && <p className="mt-3 rounded-xl bg-[#16243a] p-3 text-sm text-slate-200">{resultApiMessage}</p>}{resultPreview.length > 0 && <div className="mt-4 max-h-96 space-y-2 overflow-auto">{resultPreview.map((item) => <label key={item.matchId} className="flex cursor-pointer items-center justify-between gap-3 rounded-xl bg-[#16243a] p-3 text-sm"><span><input className="mr-2" type="checkbox" checked={selectedResults.includes(item.matchId)} disabled={item.alreadyLoaded} onChange={() => toggleResult(item.matchId)}/>{item.homeTeam} {item.homeScore} - {item.awayScore} {item.awayTeam}<span className="ml-2 text-xs text-slate-400">{new Date(item.matchDate).toLocaleDateString()}</span></span><strong className={item.alreadyLoaded ? "text-green-300" : "text-blue-300"}>{item.alreadyLoaded ? "Ya cargado" : item.currentScore ? `Actual: ${item.currentScore}` : "Nuevo"}</strong></label>)}</div>}</div>
    <div className="panel lg:col-span-2"><h2 className="text-lg font-black">Mantenimiento</h2><p className="my-2 text-sm text-slate-400">Restaura el fixture oficial versionado o actualiza los puntos de los partidos finalizados.</p><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={() => run(() => api.post("/admin/import-matches"), "Fixture oficial importado")}>Importar fixture oficial</button><button className="button-secondary" onClick={() => run(() => api.post("/admin/recalculate-points"), "Puntos recalculados")}>Recalcular puntos</button></div></div>
  </section></>;
};
